### ISSUE TITLE
Needs documentation

### ISSUE THREAD

**Issue by fatso83** [IndexXuan/vite-plugin-html-template#10]
This project seems promising, but it is not clear how to use it from the examples. When I see something about html templates, I look for some way of passing options to the template, but I cannot see how this works. For instance [this index.html file](https://github.com/IndexXuan/vite-plugin-html-template/blob/main/examples/vite-mpa-project/public/index.html) in the mpa example has this bit:
```html
    <title><%- title %></title>
```

Where is this `title` prop passed in? I looked at the code in `src/`, but I could not see any of them explicitly setting the `title` prop. I have no interest in Vue in itself, so I would just like to be able to re-use html in other html files that are to be used on the server side. Typically stuff something like this into a separate file:

```html
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
````

and then from other files I can import it
```html
<html>
<head>
    <%- commonHeader %>
    <title><%- title %></title>
</head>
```

How would that work?

**Comment by rowild** [comment]
This should work like webpack's htmlwebpackPlugin, where you define an `data` attribute.

```js
const options = {
  commonHeader: 'Common Header'
  title: 'Some title',
}

export default {
  plugins: [
    htmlTemplate(
      [...],
      data: options
    ),
  ]
}
```

(This is from memory and might need to be adjusted.)

**Comment by fatso83** [comment]
@rowild Thank you for that. This is actually showed in the [options example](https://github.com/IndexXuan/vite-plugin-html-template#options), but that options object is static/shared for the templates. If you want a different title for each template, I am not sure how we would make that happen.

**Comment by rowild** [comment]
@fatso83 I have to admit that I was not able to far to get multiple pages working. The source code here:
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/lib/options.ts#L29-L32
kind of lets me think that this does not yet work... but I might be very wrong!

However, I agree that this feature/plugin needs more love...

**Comment by fatso83** [comment]
@rowild I do [see that the hook exposes the context](https://vitejs.dev/guide/api-plugin.html#transformindexhtml), which contains the currently processed html, so seems very much possible :)

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/lib/utils.ts#L88

sorry I am on holiday. title just inject here( use title or htmlPlugin.options.title do the same of current page title, like vue cli)and html include/partial not support.
