### ISSUE TITLE
构建产物与源码不一致

### ISSUE THREAD

**Issue by bowencool** [IndexXuan/vite-plugin-html-template#14]
产物：
https://unpkg.com/browse/vite-plugin-html-template@1.0.6/dist/index.js#L5554
```
const isMPA = Object.keys(config.build.rollupOptions.input || {}).length > 0;
```

源码：
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/index.ts#L50
```
const isMPA = typeof config.build.rollupOptions.input !== 'string' && Object.keys(config.build.rollupOptions.input || {}).length > 0
```

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-html-template/actions/runs/1576477895

在发版了
