### ISSUE TITLE
Could not resolve entry module

### ISSUE THREAD

**Issue by Vidaaaa** [IndexXuan/vite-plugin-html-template#15]
I tried to use vite-plugin-mpa with vite-html-template in my project.Firstly I tried on the example called vite-mpa-project-non-standards you provided, but it didnt work.
![微信图片_20211224173216](https://user-images.githubusercontent.com/38204901/147341143-cedc95d5-e868-45ed-9997-3ed241abee01.png)

**Comment by RookieChen4** [comment]
win32下 const pageName = last(path.dirname(id).split('/')) || '' 改为const pageName = last(path.dirname(id).split(isWin32 ? '\\' : '/')) || '' 解决了这个问题

**Comment by RookieChen4** [comment]
[16](https://github.com/IndexXuan/vite-plugin-html-template/issues/16)其他可能遇到的问题

**Comment by IndexXuan** [comment]
@RookieChen4 大佬能把修复的代码，提交 PR 么。我这实在没有 window 电脑啊。你提交上来我这边 Mac/Linux 测试通过，就可以发布了。
