### ISSUE TITLE
打包的时候报错如下， The "fileName" or "name" properties of emitted files must be strings

### ISSUE THREAD

**Issue by Corgis** [IndexXuan/vite-plugin-html-template#16]
![image](https://user-images.githubusercontent.com/13865529/151685069-ed2008d3-3269-4b7a-b68b-5f47ec074143.png)

**Comment by RookieChen4** [comment]
我也遇到了这个问题
vite 中生成fileName用了 const shortEmitName = path__default.posix.relative(config.root, id) 这个方法在win32下进行如require('path').posix.relative('C:/Users/Desktop/mpa-example/src', '/src/pages/index/index.html'); 会返回'../../../../../../src/pages/index/index.html‘的错误路径。

**Comment by RookieChen4** [comment]
require('path').posix.relative('C:/Users/Desktop/mpa-example/src', 'C:/Users/Desktop/mpa-example/src/pages/index/index.html')会返回pages/index/index.html正确的路径。应该是两个全路径在win32中才能生成正确的路径，至少vite默认打包时是生成两个全路径比较在win32中。

**Comment by RookieChen4** [comment]
`resolveId(id) {
        if (id.endsWith('.html')) {
          const isMPA = typeof config.build.rollupOptions.input !== 'string' && Object.keys(config.build.rollupOptions.input || {}).length > 0
          if (!isMPA) {
            return `${PREFIX}/${path.basename(id)}`
          } else {
            const pageName = last(path.dirname(id).split(isWin32 ? '\\' : '/')) || ''
            if (pageName in (config.build.rollupOptions.input)) {
              return isWin32 ? `${process.cwd().replace(/\\/g, '/')}/${PREFIX}/${options.pagesDir.replace('src/', '')}/${pageName}/index.html` : `${PREFIX}/${options.pagesDir.replace('src/', '')}/${pageName}/index.html`
            }
          }
        }
        return null
      },`
我按照自己的需求改了下在win32是能够正常的打包了，其中应该还有许多没有考虑到的 @IndexXuan 作者什么能够考虑修改下

**Comment by IndexXuan** [comment]
@RookieChen4 thanks a lot. release v1.1.2

**Comment by gitHubxiaohu** [comment]
怎么修改的
