### ISSUE TITLE
template always use index.html

### ISSUE THREAD

**Issue by Megrax** [IndexXuan/vite-plugin-html-template#2]
I am using this plugin together with vite-plugin-mpa, and I've made the following configuration:
```javascript
// vite.config.js
plugins: [
    htmlTemplate({
      pages: {
        somePage: {
          somePage: './public/app.html',  // I want it to use 'app.html'
          title: 'somePage',
        },
      },
    }),
    mpa({
      open: '/somePage',
      scanDir: 'src/somePage/',
      scanFile: 'index.ts',
      filename: 'app.html',
    }),
]
```
And this is my public directory:
```
public
  -- app.html
  -- index.html
```
But my project used `public/index.html` for build, rather then using `public/app.html`.
Why would this happen, and how could I fix it ?

**Comment by IndexXuan** [comment]
Sorry, it is not implements. https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/lib/options.ts#L12
would you mind PR. or I will do it later.

workaround, temp use public/index.html for development, when you yarn build, it is your config with app.html.

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/index.ts#L45

It is use public/index.html by default and you can customize it. what wrong ? can you give repro demo ?

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/119778692-66290d80-befa-11eb-8f73-90d23b25bcb7.png)
it should template: 'public/app.html' not somePage: 'public/app.html'

**Comment by Megrax** [comment]
> it should template: './public/app.html' not somePage: './public/app.html'

Sorry, that's a typo in this issue, it is `template: './public/app.html'` what I am using in the code.

```javascript
// vite.config.js
plugins: [
    htmlTemplate({
      pages: {
        somePage: {
          template: './public/app.html',  // I want it to use 'app.html'
          title: 'somePage',
        },
      },
    }),
    mpa({
      open: '/somePage',
      scanDir: 'src/somePage/',
      scanFile: 'index.ts',
      filename: 'app.html',
    }),
]
```
> and you said you want app.html but you also said want index.html.

I expect it to use **app.html** , not index.html, but what actually is used is index.html :(

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/index.ts#L45

@Megrax can you add some console.log ./node_modules/vite-plugin-html-template/src/index.ts L45，it should respect with your config.template.

**Comment by IndexXuan** [comment]
I know, it is wrong pageName. this plugin now only match by src/pages.
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/index.ts#L42
I will fixed it.

**Comment by Megrax** [comment]
Thanks 👍🏾

**Comment by IndexXuan** [comment]
@Megrax It is recommended to use src/pages for MPA, it is common case.
Support your case will not very soon.

**Comment by Megrax** [comment]
Alright, but it's not appropriate for me to change the structure at this moment.
I would consider another way.
Thank you.

**Comment by IndexXuan** [comment]
I will try it today. hope not very hard.

**Comment by IndexXuan** [comment]
@Megrax 
vite-plugin-mpa@1.0.1
vite-plugin-html-template@1.0.3
example: https://github.com/IndexXuan/vite-plugin-html-template/blob/main/examples/vite-mpa-project-non-standards/vite.config.ts#L17

**Comment by IndexXuan** [comment]
any feedback ?

**Comment by Megrax** [comment]
You may close this issue for now. If there's any problem I'd open another one.
Thanks!🤩

**Comment by IndexXuan** [comment]
额，到底解决了么 ...

**Comment by Megrax** [comment]
还没有...不过我需要先理清到底是我的问题还是这个插件的问题😂到时候给你反馈

**Comment by IndexXuan** [comment]
@hex-ci 你需要的是 vite-plugin-mpa，来拥有 vue-cli 一样的 MPA 构建和 path 处理。也是我写的插件，定位不同。
vite 默认就是文件路径是啥就访问啥，src/pages/app/index.html 很正常，但是 [vite-plugin-mpa](https://github.com/IndexXuan/vite-plugin-mpa) 做了抹平

**Comment by IndexXuan** [comment]
@hex-ci 你看这个项目 examples 都是组合起来用的，为啥不二合一
1. mpa 插件只做 mpa 的事情，即自动根据文件目录结构计算出配置传给 vite，和 vue-cli 一样的体验，解决 dev 时候的 path 简化和构建后 dist 目录的简化
2. html-template 插件只做 template 工作，因为 vite 特色就是需要实体 index.html 或 src/pages/app/index.html，只解决这个单一问题。

所以想彻底拥有 vue-cli mpa 体验，两个都用，一起配合用。

**Comment by IndexXuan** [comment]
好滴 ~ 没问题。 给我插件加个链接啊，哥。
我还是坚持一个插件做一个事情，html 仅做 vite 不做的 html 模板，mpa 仅做 mpa 路径映射，哈哈。
