### ISSUE TITLE
failed to load config

### ISSUE THREAD

**Issue by WangChong99** [IndexXuan/vite-plugin-html-template#25]
![image](https://user-images.githubusercontent.com/74531242/170022167-022e2187-5faf-449f-94fe-9b748ccccc2b.png)

vite.config.js
![image](https://user-images.githubusercontent.com/74531242/170021592-7691cb91-99a4-4e85-bd67-24a93bc0cac8.png)

This one leads to a mistake, but I don't know how to avoid it
![image](https://user-images.githubusercontent.com/74531242/170021752-581459a6-5ffa-47b9-97b5-6dd0a082d700.png)

**Comment by guo897654050** [comment]
@IndexXuan 需要老哥发一下版本，这个问题已经修复。

**Comment by IndexXuan** [comment]
v1.1.4

**Comment by WangChong99** [comment]
好嘞,大佬们辛苦啦
