### ISSUE TITLE
Examples dont build

### ISSUE THREAD

**Issue by ahmed-bauercontrols** [IndexXuan/vite-plugin-html-template#3]
Steps:
1. Download the repository as zip
2. Extract to a local folder
3. Open VITE-MPA-PROJECT in VSCode
4. Run npm install
5. Run npm run build
![vs-code-screenshot](https://user-images.githubusercontent.com/88781591/132409235-b05bbd64-43b1-49a5-abe4-36c1f25838ad.png)

**Comment by IndexXuan** [comment]
ok I will figure it out.

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/132676316-c89ff377-bb5e-4f2c-90f2-7831ef1df6ba.png)
npm 7 have bug. you can use `npm 6.x` or `yarn 1.x` or `pnpm`.

**Comment by ahmed-bauercontrols** [comment]
Hi.. I do have npm version 6.14.13 and node version 14.17.3.

![mpa issue](https://user-images.githubusercontent.com/88781591/132680352-01deb003-99f3-4b73-a94a-2e116e133462.png)

**Comment by IndexXuan** [comment]
I dont know. can you provide mini repro. as you memtion I do `cd examples` and it works. for me both npm6 / yarn 1 / pnpm

**Comment by ahmed-bauercontrols** [comment]
I will try another PC and see if any other packages on my current machine are causing the problem.. Thank you for the prompt replies.

**Comment by CaiWenlie** [comment]
I met the same problem
