### ISSUE TITLE
Is there support for partials and layouts?

### ISSUE THREAD

**Issue by rowild** [IndexXuan/vite-plugin-html-template#5]
And if so, does hot-reloading work? 
(Because that's the PITA when it comes to webpack and HRM, be it pug, ejs, moustache: not hot reloading when editing partials.)

**Comment by IndexXuan** [comment]
any demo/shoucase? I dont know about that.

**Comment by rowild** [comment]
@IndexXuan you don't know about ... what exactly? Whether vite supports partials and layouts? Or about webpack showcases?

webpack gist:
https://www.google.com/search?q=webpack+ejs+partial+layout&rlz=1C5CHFA_enAT944AT944&oq=webpack+ejs+partial+layout&aqs=chrome..69i57j33i160.3720j0j7&sourceid=chrome&ie=UTF-8

Some discussion / articles on the problem with HRM and partials editing:
https://github.com/jantimon/html-webpack-plugin/issues/1397
https://newbedev.com/how-to-use-webpack-to-concat-html-pieces

Lots of stuff on that topic out there...

**Comment by IndexXuan** [comment]
vite does not evan support html template.
I use ejs for partial include html many years ago, and it is not P0 for me to implements. while PR is welcome if you can help.
Thanks.

**Comment by rowild** [comment]
> and it is not P0 for me to implements

@IndexXuan  What do you mean by "P0"?

**Comment by IndexXuan** [comment]
high priority

**Comment by rowild** [comment]
Ah! Understood! :-)
