### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by rowild** [IndexXuan/vite-plugin-html-template#7]
I use this config:

```js
import htmlTemplate from 'vite-plugin-html-template'

const htmlTemplateOptions = {
  pagesDir: 'src/pages',
  pages: {
    index: {
      template: './src/pages/index.html',
      title: 'Home Page',
    },
    subpage: {
      template: './src/pages/subpage/index.html',
      title: 'Subpage',
    },
  },
  data: {
    title: 'A title sent from data object',
  },
}

export default {
  plugins: [
    htmlTemplate(htmlTemplateOptions)
  ],
};
```

Whenever I add some text to `index.html`, I would expect Vite to hot reload. But it does not.

Here is a codesandbox:
https://codesandbox.io/s/vite-htmltemplate-test-8zh4w

(cloned from my repo here: https://github.com/rowild/vite-test)

Am I doing something wring here? Or is my expectation wrong?

**Comment by IndexXuan** [comment]
as far as I know. vite not support html file hot reload. I will test it with yarn create vite-app.
